# Generated by Django 5.1.5 on 2025-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicexam',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicexam',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
