# Generated by Django 5.1.5 on 2025-03-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exams', '0003_course_remove_electronicexam_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='electronicexam',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
