# Generated by Django 5.1.5 on 2025-03-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exams', '0005_studentresponse_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Total marks assigned by the instructor for this question.', max_digits=5),
        ),
    ]
