# Generated by Django 5.1.5 on 2025-02-04 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='student_papers',
        ),
        migrations.AddField(
            model_name='exam',
            name='student_paper',
            field=models.FileField(blank=True, null=True, upload_to='exams/student_papers/'),
        ),
        migrations.CreateModel(
            name='StudentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exams/student_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_papers', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
