# Generated by Django 5.1.5 on 2025-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/profile-default.png', null=True, upload_to='profiles/'),
        ),
    ]
