# Generated by Django 5.1.5 on 2025-03-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exams', '0005_studentresponse_feedback_and_more'),
        ('users', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_responses',
            field=models.ManyToManyField(blank=True, related_name='grades_received', to='electronic_exams.studentresponse'),
        ),
    ]
